import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import "./globals.css";
import { ReactNode, Suspense } from "react";
import TableLayout from "@/_components/tableLayout";
import { LoadingSkeleton } from "@/_components/loading";

export const metadata: Metadata = {
  title: "Snipe-it asset tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial=scale=1.0" />
      </head>
      <body>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <main className="w-full h-svh flex justify-center overflow-auto">
            <Suspense fallback={<LoadingSkeleton />}>
              <TableLayout>
                {children}
              </TableLayout>
            </Suspense>
          </main>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
